### ISSUE TITLE
Dev server won't start: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by petercr** [sw-yx/create-react-app-parcel#23]
### Cannot read property 'key' of undefined

I installed `create-react-app-parcel` globally with **npm v.6.4.0**
Then entered `crap myapp` and the process seemed to run fine. 
Then I enter the directory `/myapp` and type `npm install` **or** `yarn install`
On both Windows 10 and Ubuntu 18.04 LTS I keep getting the same error when trying to start the development server.
Yarn Version: 1.10.1

#### The Error
```
warning Pattern ["babel-core@^6.26.3","babel-core@^6.26.0","babel-core@^6.0.0"] 🚨  /home/petercr/Desktop/CRAP test/myapp/src/App.js: Cannot read property 'key' of undefined

    at new PluginPass (/home/petercr/Desktop/CRAP test/myapp/node_modules/babel-core/lib/transformation/plugin-pass.js:37:24)
    at initCloneByTag (/home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_initCloneByTag.js:60:14)
    at baseClone (/home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_baseClone.js:128:16)
    at /home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_baseClone.js:166:30
    at arrayEach (/home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_baseClone.js:160:3)
    at /home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_baseClone.js:166:30
    at arrayEach (/home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_arrayEach.js:15:9)
    at baseClone (/home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_baseClone.js:160:3)
    at /home/petercr/Desktop/CRAP test/myapp/node_modules/lodash/_baseClone.js:166:30
```
##### Then it just sits there :disappointed: :cry: 
I then stop the process by hitting `Ctrl + C`
I don't know how to fix this error. But here's a screenshot of it if that helps.
Thanks this sounds like a really cool project :sunglasses: :+1: :smiley: 

![crap_error_screenshot](https://user-images.githubusercontent.com/26460352/46174758-e98c8f80-c277-11e8-8efe-599edd8c198e.jpg)

**Comment by gustavengstrom** [comment]
I am having the same problem. Everything was working fine until I decided to upgrade npm today. I tried downgrading but could not get it to work (maybe didn't downgrade back to the correct version). Would be good to no which npm version other users with working CRAP apps have installed...

**Comment by IvoPereira** [comment]
Having the same issue when installing from scratch.

Using node v10.6.0 with npm 6.3.0.

**Comment by jonathanvoelkle** [comment]
I had the same problem, found a workaround:
replace in `src/App.js`
```js
  state = { toggle: true };
```
with
```js
  constructor (props) {
    super(props)
    this.state = { toggle: true };
  }
```

**Comment by jonathanvoelkle** [comment]
@petercr  what does the browser console of the `localhost:1234` say?

**Comment by petercr** [comment]
@jonathanvoelkle Thank I had forgot to check 😉 It turns out I just forgot to add `this` infront of `this.state`
That fixed the problem like you had said 👍 🥇 
Everything seems to be working fine now, thanks 👏 👏
