### ISSUE TITLE
yarn start results in Unexpected token function

### ISSUE THREAD

**Issue by danpatnate** [sw-yx/create-react-app-parcel#4]
Trying to start the app with yarn and receiving the following:

```
.../node_modules/react-scripts-parcel/scripts/start.js:131
    async function start() {
          ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tsiq-swyx** [comment]
hello - what version of node are you running? i am on node v9.4.0 and create-react-app-parcel v0.0.17 and it works fine.

**Comment by tsiq-swyx** [comment]
that async dependency wasn't required anyway, so i removed it. thanks for flagging it :)

**Comment by danpatnate** [comment]
Nice, and yes I was on version 6.9.0, switching to 9.5.0 did the trick 👍thanks!
